server:
  port: 10086

spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      # 此应用为注册中心，false：不向注册中心注册自己。
    register-with-eureka: false
    fetch-registry: false

