server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api  #添加路由前缀
  routes:
    item-service: /item/** #商品微服务
    search-service: /search/** #搜索微服务
    upload-service: #文件上传微服务（忽略前面upload）
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    user-service: /user/** #用户微服务
    auth-service: /auth/** #授权中心微服务
    cart-service: /cart/** #购物车微服务
    order-service:      #订单微服务
      path: /order/**


  ignored-services: upload-service #文件上传不通过网关，减少服务器压力
  ignored-patterns: /upload/**
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: #配置禁用使用的头信息，这里设置为null，否则set-cookie无效


hystrix:
  command:
    default:
      excution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000   #熔断超时时长为5000ms

ribbon:
  ConnectionTimeout: 1000 #ribbon链接超时时长
  ReadTimeout: 3500 #ribbon读取超时时长
  MaxAutoRetriex: 0 #当前服务重启次数
  MaxAutoRetriexNextServer: 0 #切换服务重启次数


leyou:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter: #设置白名单，不拦截
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/send
    - /api/item